- name: gather /etc/resolv.conf file stat
  stat:
    path: /etc/resolv.conf
  register: resolv_conf_file_stat

- name: remove symlink /etc/resolv.conf
  file:
    state: absent
    path: /etc/resolv.conf
  when: resolv_conf_file_stat.stat.islnk is defined and resolv_conf_file_stat.stat.islnk

- name: unprotect /etc/resolv.conf for writing by Ansible
  file:
    path: /etc/resolv.conf
    attributes: 'e'
  when: resolv_conf_file_stat.stat.exists == True and resolv_conf_file_stat.stat.islnk is not defined

- name: template /etc/resolv.conf
  template:
    src: templates/etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0444

- name: protect /etc/resolv.conf from being overwritten
  file:
    path: /etc/resolv.conf
    owner: root
    group: root
    mode: 0444
    attributes: 'ie'
